apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  labels:
    app: nginx
data:
  nginx.conf: |
    # Nginx configuration goes here
    worker_processes 1;
    events { worker_connections 1024; }
    http {
      server {
        listen 8080;
        location / {
          root /usr/share/nginx/html;
          index index.html;
        }
      }
    }