apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: movie-db

spec:
  serviceName: movie-db
  replicas: 1
  selector:
    matchLabels:
      app: movie-db
  template:
    metadata:
      labels:
        app: movie-db
    spec:
      containers:
      - name: movie-db
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: "{{ .Values.env.POSTGRES_DB }}"
        - name: POSTGRES_USER
          value: "{{ .Values.env.POSTGRES_USER }}"
        - name: POSTGRES_PASSWORD
          value: "{{ .Values.env.POSTGRES_PASSWORD }}"
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: postgres-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "{{ .Values.volume.storageClass }}"
      resources:
        requests:
          storage: "{{ .Values.volume.size }}"
