apiVersion: v1
kind: Service
metadata:
  name: cast-service
  labels:
    app: cast-service

spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}   # ✅ Doit être un entier, pas une chaîne
      targetPort: 80
  selector:
    app: cast-service
